services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ecommerce-adminer
    restart: unless-stopped
    ports:
      - '8081:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
